export const REGISTER = 'REGISTER'
export const REGISTER_FULFILLED = 'REGISTER_FULFILLED'
export const REGISTER_REJECTED = 'REGISTER_REJECTED'

export const GET_QUESTION = 'GET_QUESTION'
export const GET_QUESTION_FULFILLED = 'GET_QUESTION_FULFILLED'
export const GET_QUESTION_REJECTED = 'GET_QUESTION_REJECTED'

export const SEND_ANSWER = 'SEND_ANSWER'
export const SEND_ANSWER_FULFILLED = 'SEND_ANSWER_FULFILLED'
export const SEND_ANSWER_REJECTED = 'SEND_ANSWER_REJECTED'